version: "3.9"
services:
  mongo:
    container_name: mongodb
    image: mongo:5.0
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  customer-db-service:
    container_name: customer-db-service
    build: .
    env_file:
      - .env
    ports:
      - ${RMI_PORT}:${RMI_PORT}
    depends_on:
      - mongo
    links:
      - mongo:local_mongo
