version: "3.9"
services:
  user-ldap-server:
    container_name: user-ldap-server
    image: osixia/openldap:latest
    restart: unless-stopped
    ports:
      - '10389:10389'
      - '10636:10636'
    command: ["--copy-service"]
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_BASE_DN: "dc=ad,dc=teamF,dc=net"
      LDAP_ORGANISATION: "Musichop F"
      LDAP_DOMAIN: "ad.teamF.net"
      LDAP_TLS: "false"
      LDAP_PORT: "10389"
    volumes:
      - ./employee-data.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap-data.ldif
  mongo:
    container_name: mongodb
    image: mongo:5.0
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - customer_backend
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  customer-db-service:
    container_name: customer-db-service
    build: .
    env_file:
      - .env
    ports:
      - ${RMI_PORT}:${RMI_PORT}
    networks:
      - customer_backend
    depends_on:
      - mongo
    links:
      - mongo:local_mongo

networks:
  customer_backend:
    driver: bridge