version: "3.9"
services:
  user-ldap-server:
    networks:
      - inter_server_connection
  customer-db-service:
    networks:
      - inter_server_connection

networks:
  customer_backend:
    driver: bridge
  inter_server_connection:
    name: inter_server_connection
    driver: bridge