version: "3.9"
services:
  mongo:
    container_name: mongodb
    image: mongo:5.0
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - customer_backend
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  customer-db-service:
    container_name: customer-db-service
    build: .
    env_file:
      - .env
    ports:
      - ${RMI_PORT}:${RMI_PORT}
    networks:
      - customer_backend
#      - rmi_connection
    depends_on:
      - mongo
    links:
      - mongo:local_mongo

networks:
  customer_backend:
    driver: bridge
#  rmi_connection:
#    name: rmi_connection
#    driver: bridge