version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - customer-db.env
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  customer-db-service:
    container_name: customer-db-service
    build: .
#    ports:
#      - "1099:1099"
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - customer-db.env