apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-data-provider
spec:
  template:
    metadata:
      name: mongo-data-provider
      labels:
        app: mongo-data-provider
    spec:
      containers:
        - name: mongo-data-provider
          image: team-f-mongo-data-provider
          imagePullPolicy: Never
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
            - name: MONGO_INITDB_DATABASE
              value: customerDb
            - name: MONGO_USERNAME
              value: mongo
            - name: MONGO_PASSWORD
              value: mongo
      restartPolicy: Never
  backoffLimit: 1