apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ldap-server
spec:
  selector:
    matchLabels:
      app: user-ldap-server
  template:
    metadata:
      name: user-ldap-server
      labels:
        app: user-ldap-server
    spec:
      containers:
        - name: user-ldap-server
          image: osixia/openldap:latest
          env:
            - name: LDAP_ADMIN_PASSWORD
              value: admin
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "true"
            - name: LDAP_BASE_DN
              value: "dc=ad,dc=teamF,dc=net"
            - name: LDAP_ORGANISATION
              value: "Musicshop F"
            - name: LDAP_DOMAIN
              value: "ad.teamF.net"
            - name: LDAP_TLS
              value: "false"
            - name: LDAP_PORT
              value: "10389"
          ports:
            - name: ldap1
              containerPort: 10389
            - name: ldap2
              containerPort: 10636
---
apiVersion: v1
kind: Service
metadata:
  name: user-ldap-server
spec:
  selector:
    app: user-ldap-server
  ports:
    - name: ldap1
      port: 10389
      targetPort: ldap1
    - name: ldap2
      port: 10636
      targetPort: ldap2